backend:
  environment_variable_example: test
prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: 
        kubernetes.io/ingress.class: nginx
        #nginx.ingress.kubernetes.io/use-regex: "true"
        #nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - chart-monitoring.com
      #path: /prometheus
      path: /
      #pathType: ImplementationSpecific
    global:
      ## How frequently to scrape targets by default
      ##
      scrape_interval: 1m
      ## How long until a scrape request times out
      ##
      scrape_timeout: 10s
      ## How frequently to evaluate rules
      ##
      evaluation_interval: 1m
  
  ## Prometheus server ConfigMap entries
  ##
  serverFiles:
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/config/alerting_rules.yml
        - /etc/config/rules
        - /etc/config/alerts

      scrape_configs:
        - job_name: 'test-backend'
          static_configs:
            - targets:
              - test-backend:1234
