services:
  node_exporter:
    container_name: node_exporter
    image: prom/node_exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest