apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "backend.fullname" . }}-pod-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
