apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backend.fullname" . }}-pod-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "backend.fullname" . }}-pod-reader
  apiGroup: rbac.authorization.k8s.io
