# Run with: ansible-playbook -i ../terraform-openstack/openstack-inventory.txt deploy.yml
---
# Begin: Prerequisites
- hosts: all
  name: Prerequisites
  gather_facts: false
  user: ubuntu
  become: false
  vars:
    helm_version: "v3.14.0"
    kubectl_version_url: "https://dl.k8s.io/release/stable.txt"

  tasks:
    - name: Wait for ssh
      ansible.builtin.wait_for_connection:
    - name: Wait for cloud-init to finish
      ansible.builtin.raw: while [ ! -f /var/lib/cloud/instance/boot-finished]; do sleep 10s; done
      retries: 10
      delay: 1




- name: Install Minikube
  hosts: all
  gather_facts: false
  user: ubuntu
  become: false
  tasks:

  - name: Start Minikube
    become: false
    shell: |
      minikube start 
    environment:
      MINIKUBE_IN_STYLE: "true"

  - name: Check Minikube profiles
    ansible.builtin.command: minikube profile list --output=json
    register: profile_list

  - name: Enable Ingress add-on if profile exists
    ansible.builtin.command: minikube addons enable ingress --profile=minikube
    when: "'minikube' in profile_list.stdout"
    register: ingress_result

  - name: Show result
    ansible.builtin.debug:
      var: ingress_result.stdout

- name: Install Helm on Debian/Ubuntu
  hosts: all
  become: true
  gather_facts: false
  user: ubuntu
  become_user: root 
  vars:
    helm_version: "v3.14.0"
    kubectl_version_url: "https://dl.k8s.io/release/stable.txt"

  tasks:

    - name: Install Helm via official script
      become: true
      ansible.builtin.shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm


 