# Run with: ansible-playbook -i ../terraform-openstack/openstack-inventory.txt deploy.yml
---
# Begin: Prerequisites
- hosts: all
  name: Prerequisites
  gather_facts: false
  user: ubuntu
  become: false
  vars:
    helm_version: "v3.14.0"
    kubectl_version_url: "https://dl.k8s.io/release/stable.txt"

  tasks:
    - name: Wait for ssh
      ansible.builtin.wait_for_connection:
    - name: Wait for cloud-init to finish
      ansible.builtin.raw: while [ ! -f /var/lib/cloud/instance/boot-finished]; do sleep 10s; done
      retries: 10
      delay: 1


- name: Add prometheus Helm repo
  ansible.builtin.command:
    cmd: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 

- name: Add Grafana Helm repo
  ansible.builtin.command:
    cmd: helm repo add grafana https://grafana.github.io/helm-charts

- name: Move images from host Docker to Minikube
  hosts: all
  user: ubuntu
  become: false
  tasks:

    - name: Load backend image into Minikube
      shell: minikube image load backend:latest 

    - name: Load frontend image into Minikube
      shell: minikube image load frontend:latest

    - name: Load oven image into Minikube
      shell: minikube image load oven:latest

- name: Build Helm dependencies and install chart
  hosts: all
  become: false   # run as the user with Helm configured (usually ubuntu)
  tasks:
    - name: Build Helm dependencies
      ansible.builtin.command: helm dependency build deployment/charts/application/
      args:
        chdir: /home/ubuntu/W3M20035.1-cloud-infrastructures
      register: helm_dep_result

    - name: Install Helm chart
      ansible.builtin.command: helm install test deployment/charts/application/
      args:
        chdir: /home/ubuntu/W3M20035.1-cloud-infrastructures
      register: helm_install_result

- name: Add chart-example.com to /etc/hosts
  hosts: all
  become: true   # needed to modify /etc/hosts
  tasks:
    - name: Ensure chart-example.com entry exists in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.49.2 chart-example.com"
        state: present

- name: Add chart-grafana.com to /etc/hosts
  hosts: all
  become: true   # needed to modify /etc/hosts
  tasks:
    - name: Ensure chart-grafana.com entry exists in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.49.2 chart-grafana.com"
        state: present

- name: Add chart-monitoring.com to /etc/hosts
  hosts: all
  become: true   # needed to modify /etc/hosts
  tasks:
    - name: Ensure chart-monitoring.com entry exists in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.49.2 chart-monitoring.com"
        state: present